### ISSUE TITLE
Change direction of slide in

### ISSUE THREAD

**Issue by tsvecak** [rottenstudios/menufullpage#1]
Hey there i am just curious is there way to make it come from right side?

**Comment by rottenstudios** [comment]
Hi, yes, if u change:
1) side:"left" -> slide:"right" (first line of menuFullpage.min.js)
2) .panel {
    position: fixed;
    right: -100%; /*left or right and the width of your navigation panel*/ 
    width: 100%;
} (line 7 on menufullpage.css)
