### ISSUE TITLE
When open in mobile (Screen resolution:768x1280) and below

### ISSUE THREAD

**Issue by LeoJamesTan** [rottenstudios/menufullpage#2]

**Comment by rottenstudios** [comment]
Hi, i think you have some problem with your html code..  Is your website onepage? have you an ID for home section? Send me a screen :)

**Comment by LeoJamesTan** [comment]
Hi, is the same error in your downloadable version of your menufullpage. Yes there is ID for home section and other section as well. Bro, it's not just home, when it scroll down all the way to the end of page, it is unable to go back up to any section of the page. It is workable on screen resolution width of 1024 and above. but when preview in width 769 and below, the error will occur.

**Comment by rottenstudios** [comment]
Ok, apparently the problem is Smooth Scroll

<script>
         TRY TO REMOVE THIS LINE
        $(document).ready(function() {
                $('.menu-link').menuFullpage();
        });
</script>

and "data-scroll" on the tag "a"
you can replace it with another smooth scroll

**Comment by LeoJamesTan** [comment]
ok Thanks!
